### PR TITLE
updates for v3 api sync

### PR DESCRIPTION
**Pull request by ksigler7**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-oai?pullRequest=15) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-oai?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-oai?pullRequest=15) it.</sub>

**Comment by thinkingserious** [comment]
Hi @ksigler7,

We will also need an updated `oai_stoplight.json`.

Details are here: https://wiki.sendgrid.net/pages/viewpage.action?spaceKey=DX&title=Participation+and+Contribution+Policy#ParticipationandContributionPolicy-swagger

Thanks!

**Comment by ksigler7** [comment]
@thinkingserious thanks for the link to the wiki!

**Comment by ksigler7** [comment]
@thinkingserious okay, I've added all of the latest changes (we slipped some more in this morning). Does it look good to you? We've decided that we're not going to do release notes (since it would probably take days to parse through a years worth of changes) and just make sure we update them from here on out. If it looks good, please merge!

**Comment by thinkingserious** [comment]
Hi @ksigler7,

Could you please provide some details on what was changed? It looks like almost the whole file was modified and trying to determine what exactly was changed is difficult: https://github.com/sendgrid/sendgrid-oai/pull/15.patch

Was is simply documentation? Or are there structural changes also? 

Thanks!

With Best Regards,

Elmer

**Comment by ksigler7** [comment]
Hey @thinkingserious, Unfortunately, it looks like these files haven't been updated in this repo since last summer. So, I can tell you that Carly and I made mostly documentation changes - the only structural changes were adding the optional `on-behalf-of` header where relevant. So, that's the last month - I'm not sure what changed over the 10 months before that, and I'm not sure how I would find out.

**Pull request merged**
